services:
  # web:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   command: ["/app/main"]
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-fakedb}
    ports:
      - 5432:5432


volumes:
  postgres_data:
